name: FarmingTycoon
version: 1.0.6
main: it.tristana.farming.Main
description: Tycoon with Minecraft crops
author: Massimiliano Micol
depend: [TristanaCommons, WorldEdit]
softdepend: [FastAsyncWorldEdit]